version: '3.9'
services:
  pg:
    image: postgres:14.7-alpine
    container_name: pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=metopia123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass "redis"
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
