INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (7, 'Business Strategy for Flexible Modular Living in Germany', 'Nuremberg (Gostenhof), Germany', '{11.058193,49.447666}', '{Germany,"Box Community","Modular Living","Business Strategy"}', 'This research project analyzes the business strategy of the Box Community in Germany. It answers the questions of why living should be newly defined, where can possible locations be found, what are different revenue streams, and how a resulting strategy could look like to realize the Box Community.', 6, 11, 1, '#07FFF2FF');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (9, 'Reflection on Box Community in Sao Paulo', 'São Paulo', '{-46.6334,-23.5507}', '{}', '', 1, 13, 1, '#FF0000');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (20, '小闪-针对年轻人摊位经济的新能源共享三轮车', '上海市', '{121.46947894381701,31.23194399924772}', '{三轮车,快闪,共享}', '小闪是一个精致小巧、可以轻便移动的可折叠展开的极致空间。通过模块化、定制化的方式让用户可以最大限度的布置自己的摊位。如三轮车尾部的操作台，可以进行模块化的更换，美食摊主可以换成饮食制作台、手工摊主可以换成手工操作台、销售摊主可以换成直播模块等；车尾底部除了作为基础的储物空间外，摊主可以根据实际需求拖挂附件。', 8, 24, 1, '#FF1598FF');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (19, '时空之岛元宇亩劳动教育系统', '上海市向明初级中学附属崇明区江帆中学', '{121.43378236358643,31.632176347673532}', '{元宇宙教育,元宇宙花园}', '本项目在全育育人背景下，依托江帆中学屋顶智能种植农场，针对劳动课程中存在的吸引力不足、教学时间利用不充分、学生学习不深入三大痛点，设计线上线下相结合的元宇宙劳动教学系统。空间设计上，以时间为线索，设计三大主要空间：旧日回响空间中，学生可通过全息投影回溯植物的过去，以此为参考调整种植行为；同步幻境空间复制真实世界中的劳动场地，学生可随时随地登入元宇宙查看植物生长状况；未来之梦空间允许学生通过与虚拟装置交互了解植物的梦想，即植物成熟后在生产消费环节的用途。此外，我们设计了配套的植物拟人系统，通过为植物赋予人格、装扮等信息，增强学生与植物的情感联系，并通过梦想任务系统引导学生逐步深入地学习种植知识。', 5, 23, 1, '#FF8507FF');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (17, '世纪灵境', '世纪广场', '{121.47518301082367,31.237338782231333}', '{}', '结合RAR城元宇宙商业价值生态的理论研究基础，我们依托上海南京路世纪广场元宇宙设计项目为蓝本，以验证我们提出的理论框架。南京路作为中华第一商业大街，融合了万国建筑群老上海的庄重、历史建筑与现代楼宇的交汇以及未来氛围的霓虹色彩，是对过去的庄重包容，对现代的极致演绎，对未来的先锋探索；世纪广场是南京路上最重要的开敞空间节点，它链接东西外滩，成为南京路的人流集散点，主体建筑以镜面为特点，脱胎于“上海”“海上”，向起源致敬。我们以“镜遇”为主题，通过7个章节故事线提供RAR多维度体验，以刺激南京路商业街消费、提升唤新老字号品牌，为游客提供一场过去、现在和未来交织的“多重宇宙”体验。', 4, 21, 1, '#07FF95FF');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (29, 'Rhythm Racer——针对智能座舱设计的多模态互动VR音游', '南山区', '{113.92514061178404,22.535834955817702}', '{智能座舱,VR,音游}', 'Rhythm Racer是一款针对智能座舱设计的车载多模态互动VR音游，针对中青年车主“车内半小时”场景，以音乐为桥梁，通过轻松短时的游戏节奏和紧张刺激的节奏敲击感和基于位置的轻对战模式，将车内方向盘、操纵杆、踏板等硬件变为游戏外设，发挥车内载体优势，调动全感官放松，在创新音游交互形式的同时赋予玩家虚实结合的沉浸感，帮助玩家释放压力，做回自我。', 10, 33, 1, '#D8D8D8FF');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (10, 'WEB3.0背景下国内共享空间IP设计-MARSCAT', '同济大学(四平路校区)', '{121.49752804983218,31.28539599485083}', '{web3.0}', '随着元宇宙的爆火，数字藏品/NFT内容被越来越多的人看到。而这其中自然而然就带动了IP内容的发展，火星猫IP以新锐白领和Z时代人群为主要的用户人群，从航空航天的角度出发，贴合航天文化并融入了潮玩元素和宠物元素。打造出了3套围绕火星主题的IP形象并通过其衍生品来实现MARSCAT价值的传递。让MARSCAT来自火星的slogan占据用户的心智。', 9, 14, 1, '#64FF00FF');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (25, 'Web3.0背景下国内共享空间IP设计', '含舍共享智能空间(五四广场店)', '{120.37460198851039,36.063345031462575}', '{}', '本次作品关注了web3.0、区块链、智能合约及相关前沿技术领域，结合环境设计学科背景，选择共享空间作为研究的出发点。重点探索了不同学科领域下共享空间的定义、现状和问题，以及在现有条件下，web3.0技术在共享空间这一商业模式下的赋能切入点以及应用方向。期待本次交叉领域的研究能够推动共享空间准确学术定义的建立。
本次作品运用桌面和实际调研、相关领域论文研究；蓝海战略、市占曲线等商业模型，深入分析商业模式的价值闭环，明确通过“高中低”三步走战略、KOL牵头的粉丝经济打造IP价值。
本次作品最终呈现形式是IP的UI设计、环境设计。
', 9, 29, 1, '#64FF00FF');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (8, 'Bloom AUTO 生成式NFT车衣套装及体验设计', '四平路街道', '{121.511978,31.27659}', '{车衣,nft,元宇宙}', '每位车主的车都是独一无二的。车承载着车主的追求、偏好，也体现着车主独特的生活状态与轨迹。正因为车主与车所相处的时间，让ta的车如此与众不同，仿若老友。正如世界上没有任何一株相同的植物，植物所蕴含的数字密码也暗含着它的独特谜语。我们将通过有趣的模型，解读用户的[个人及车辆]信息，转换为与用户相关联的专属生物密码，并在元宇宙中生成用户的专属虚拟车衣NFT，与用户一同为爱车赋予新的生命，并带来更多体验；在元宇宙中，我们打造像植物沟通一样自然的交互方式，独特的NFT社群能让车主感受到可持续的、返璞归真的新社交体验，并更好地与线下生活相结合，构建全新车友生态。', 1, 12, 1, '#FF0000');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (12, '光交互老人智慧卡设计', '杨浦区', '{121.5216539027329,31.261676571668236}', '{}', '本项目设计光交互智慧老人卡，基于光交互技术，为老年人设计满足日常生活的便携式一卡通，促进数字无障碍适老化改造。结合落地性与功能性方面的考量，我们规划了基础版与高级版两个版本并预估定价。外形与硬件部分，制作了3d打印且屏幕可显示的智慧卡原型。软件部分，考虑到老人使用智能设备时存在的数字鸿沟，简化智慧卡每个功能的操作，同时配备子女端管理app，对双端进行功能设计与界面设计。', 1, 18, 1, '#FF0000');
INSERT INTO "enroll_product_dif_regional" ("id", "name", "regional", "point", "tags", "description", "category_id", "group_id", "fromtype_id", "color") VALUES (16, 'VIRTOUCH', '静安设计节', '{121.43938949440576,31.235041224785547}', '{虚实结合,展览,场域,行星引力}', '新的观展媒介、新的观展体验、新的观展纪念品、新的观展叙事，VirTouch。VirTouch将融合了具身交互的个性化首饰嵌入观展流程，提取指尖感应这一意象，选择以半截指套作为载体。即便观众无法触碰真实的作品，也能通过指套感受艺术的质感，感受创作的温度。通过触觉反馈的方式实现观众与展品间的实时对话与互动，由VirTouch记录下的观展动线、展品互动记录等数据被转译为生成式的计算程序，每一位观众在观展结束后都能够获取以行星为主题的、承载着自我观展经验的、独一无二的NFT作品。VirTouch，以虚实相生为关键词重塑展览引力场。', 10, 16, 1, '#D8D8D8FF');
