INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (11, 'Box Community', '{"Manuel Sauer"}', 4);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (12, '可持续时尚第三小组', '{李玉希,赵永慧,赵心悦,文绮颖}', 5);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (13, 'Jacqueline Chen', '{"Jacqueline Chen"}', 10);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (14, 'MARSCAT', '{胡钟元,张一鸣}', 14);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (15, 'RAR城元宇宙-文化组', '{张慕财,陈乐恒}', 16);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (16, '可持续时尚气氛组', '{张润花,卢旭,陈佳怡,姚奕欣,程瑶}', 18);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (17, '人工智能艺术品价值判断', '{杜木瑞,张达}', 24);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (18, '可持续时尚第6组', '{赫然,廖一菲,金茹画}', 26);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (19, 'sl:Co-Mint小队', '{陈雪儿,张曼}', 29);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (20, '可持续时尚Group1', '{缪绮阳,张雅菁,江姿颖}', 12);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (21, 'RAR城元宇宙：数字与商业', '{范思琦,张鑫,蒋沐,戚致远}', 32);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (22, 'MetaWeb', '{王者鹏,陆尧}', 36);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (23, '元宇宙教育组', '{陆子文,陈瑾霄,李禹慧,蔡博慧,侯绪彤,褚初寒}', 38);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (24, '新能源三轮车组', '{尹硕,徐艺丹,黄佳捷,魏有晟}', 45);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (25, '摩尔组', '{古坷懿,罗瑶,陈星珲}', 49);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (26, '面向儿童的手机操作系统智能助手小组', '{陈灿杰,李欣,王旭光}', 52);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (27, '基于王小慧艺术馆展览的实体与虚拟首饰设计', '{陈河润,顾天润,冯泗衡,田沁锋}', 55);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (28, '黄舒婷+钟嘉欣：glamping', '{黄舒婷,钟嘉欣}', 59);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (30, '杨政昂', '{杨政昂}', 61);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (31, 'RAR城元宇宙-数字与功能', '{王浩杰,吴雨蔚,黑静好,曹焰铖}', 62);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (32, '露营场景下的新能源储能产品设计', '{韩啸}', 66);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (29, 'Web3.0第一组', '{彭慕遥}', 67);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (33, '自拟组', '{柏玥}', 68);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (34, 'Web3.0', '{吴鹏飞}', 69);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (36, '李佳诺组', '{李佳诺}', 74);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (35, '虚拟可持续时尚第五组', '{宋志豪,魏紫东来,郝超雄,黄子沅}', 70);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (37, '王瑞贞组', '{王瑞贞}', 75);
INSERT INTO "enroll_group" ("id", "name", "member", "leader_id") VALUES (38, '浦江森林公园', '{邵金鑫}', 76);
