# Generated by Django 4.1.4 on 2022-12-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_content_model_alter_content_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fromtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='来源名')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fromtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enroll.fromtype', verbose_name='作品来源'),
        ),
    ]
