# Generated by Django 4.1.3 on 2022-12-19 13:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_fromtype_product_fromtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创作时间'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='作者头像地址'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='作者性别'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enroll.occupation', verbose_name='职业名称'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='point',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2, verbose_name='出生地经纬度'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='regional',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='出生地'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='个性签名'),
        ),
    ]
