# Generated by Django 4.1.3 on 2022-12-19 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_content_date_alter_partner_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='avatar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default='{}', size=None, verbose_name='作者头像'),
            preserve_default=False,
        ),
    ]
