# Generated by Django 4.1.4 on 2022-12-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='用户')),
                ('date', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enroll.content', verbose_name='作品内容')),
            ],
        ),
        migrations.CreateModel(
            name='social_share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='用户')),
                ('date', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enroll.content', verbose_name='作品内容')),
            ],
        ),
        migrations.CreateModel(
            name='social_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='用户')),
                ('date', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enroll.content', verbose_name='作品内容')),
            ],
        ),
    ]
