# Generated by Django 4.0.4 on 2023-08-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_initial'),
        ('enroll', '0007_social_view_social_share_social_like'),
    ]

    operations = [
    ]
