# Generated by Django 4.0.4 on 2023-08-16 21:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('type', models.CharField(max_length=20, verbose_name='样例类型')),
            ],
        ),
        migrations.CreateModel(
            name='custome_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='建筑名称')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('size', models.IntegerField(verbose_name='点赞数')),
                ('type', models.CharField(max_length=20, verbose_name='案例类型')),
                ('designer', models.CharField(max_length=50, verbose_name='设计者')),
                ('description', models.TextField(max_length=800, verbose_name='描述')),
                ('mid_time', models.DateField(verbose_name='中期时间')),
                ('mid_cover', models.CharField(max_length=50, verbose_name='中期封面')),
                ('term_time', models.DateField(verbose_name='中期时间')),
                ('term_cover', models.CharField(max_length=50, verbose_name='终期封面')),
                ('video', models.CharField(max_length=50, verbose_name='视频')),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('mid_album', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('term_album', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='excellent_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='建筑名称')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('url', models.CharField(max_length=200, verbose_name='建筑名称')),
                ('size', models.IntegerField(verbose_name='点赞数')),
                ('designer', models.CharField(max_length=50, verbose_name='设计者')),
                ('supplier', models.CharField(max_length=100, verbose_name='供应商')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('area', models.IntegerField(verbose_name='面积')),
                ('description', models.TextField(verbose_name='描述')),
                ('img', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('type', models.CharField(max_length=20, verbose_name='样例类型')),
            ],
        ),
    ]
