# Generated by Django 4.0.4 on 2023-08-16 22:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custome_case',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='designer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设计者'),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='mid_album',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='mid_cover',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='中期封面'),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='mid_time',
            field=models.DateField(blank=True, null=True, verbose_name='中期时间'),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='term_album',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='term_cover',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='终期封面'),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='term_time',
            field=models.DateField(blank=True, null=True, verbose_name='中期时间'),
        ),
        migrations.AlterField(
            model_name='custome_case',
            name='video',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='excellent_case',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='excellent_case',
            name='area',
            field=models.IntegerField(blank=True, null=True, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='excellent_case',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='excellent_case',
            name='designer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='设计者'),
        ),
        migrations.AlterField(
            model_name='excellent_case',
            name='img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='excellent_case',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='excellent_case',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='url'),
        ),
    ]
